### ISSUE TITLE
[RPC] enpoint Error

### ISSUE THREAD

**Issue by Damantino** [0xPolygon/cdk-erigon#164]
#### System information

output of git branch
```bash
* (HEAD detached at v0.0.3-alpha)
  zkevm
```

- 22.04.1-Ubuntu LTS
- Tag v0.0.3-alpha

#### Config File

````yaml

datadir :  '/mnt/ethereum/cdk-erigon-data/hermez-mainnet/'
chain : "hermez-mainnet"
http : true
private.api.addr : "0.0.0.0:7092"
zkevm.l2-chain-id: 1101
zkevm.l2-sequencer-rpc-url: "https://zkevm-rpc.com"
zkevm.l2-datastreamer-url: "stream.zkevm-rpc.com:6900"
zkevm.l1-chain-id: 1
zkevm.l1-rpc-url: "http://localhost:8545/"
zkevm.l1-polygon-rollup-manager: "0x5132A183E9F3CB7C848b0AAC5Ae0c4f0491B7aB2"
zkevm.l1-rollup: "0x519E42c24163192Dca44CD3fBDCEBF6be9130987"
zkevm.l1-matic-contract-address: "0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0"
zkevm.l1-ger-manager-contract-address: "0x580bda1e7A0CFAe92Fa7F6c20A3794F169CE3CFb"
zkevm.l1-topic-verification: "0x9c72852172521097ba7e1482e6b44b351323df0155f97f4ea18fcec28e1f5966"
zkevm.l1-topic-sequence: "0x3e54d0825ed78523037d00a81759237eb436ce774bd546993ee67a1b67b6e766"
zkevm.l1-block-range: 20000
zkevm.l1-query-delay: 6000
zkevm.l1-first-block: 16896700
zkevm.rpc-ratelimit: 250
zkevm.datastream-version: 2

externalcl: true
http.api : ["eth","debug","net","trace","web3","erigon","zkevm"]
````
Erigon Command (with flags/config):

`./build/bin/cdk-erigon  --config="/mnt/ethereum/cdk-erigon/hermezconfig-mainnet.yaml"`

#### Expected behaviour

When I curl to a zkevm RPC I would expect data coming out:

````bash
curl --http1.1 -X POST http://nodeUrl:7092 \
-H "Content-Type: application/json" \
-d '{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "zkevm_batchNumber",
  "params": []
}'
curl: (1) Received HTTP/0.9 when not allowed
````

#### Actual behaviour

````bash
curl: (1) Received HTTP/0.9 when not allowed
````

#### Steps to reproduce the behaviour

Launch node, wait untill synchronizes and make curl petition.

#### Backtrace

Notably an error happens when I launch the program

````bash
EROR[02-29|13:05:31.023] could not start RPC api for engine: could not start RPC api: listen tcp 127.0.0.1:8551: bind: address already in use
````

Is error related? If so, how can I change the RPC port?
