### ISSUE TITLE
[RPC] RPC method "zkevm_batchNumberByBlockNumber"  not working when requesting against rpcdaemon

### ISSUE THREAD

**Issue by Damantino** [0xPolygon/cdk-erigon#338]
#### System information

output of git branch
```bash
* (HEAD detached at v1.0.6)
  zkevm
```

- 22.04.1-Ubuntu LTS
- Tag v1.0.6

#### Config File

````yaml
chain: "hermez-mainnet"
http: true
http.port: 8550
private.api.addr: "localhost:9091"
zkevm.l2-chain-id: 1101
zkevm.l2-sequencer-rpc-url: "https://zkevm-rpc.com"
zkevm.l2-datastreamer-url: "stream.zkevm-rpc.com:6900"
zkevm.l1-chain-id: 1
zkevm.l1-rpc-url: "http://myL1node.com:8545/"
zkevm.l1-matic-contract-address: "0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0"
zkevm.l1-block-range: 20000
zkevm.l1-query-delay: 6000
zkevm.l1-first-block: 16896700
zkevm.rpc-ratelimit: 250
zkevm.datastream-version: 2

externalcl: true
http.api: ["eth", "debug", "net", "trace", "web3", "erigon", "zkevm"]
````
Erigon Command (with flags/config):

`./build/bin/cdk-erigon  --config="/mnt/ethereum/cdk-erigon/hermezconfig-mainnet.yaml" --ws`

Erigon RPC

`./build/bin/rpcdaemon --datadir=/path/to/cdk-erigon/data --txpool.api.addr=localhost:9091 --private.api.addr=localhost:9091  --http.api=eth,erigon,web3,net,debug,trace,txpool,zkevm --ws --ws.compression`

#### Expected behaviour

When I curl to get batch number it gets delivered.

````bash
> curl --request POST      --url http://localhost:8545/    --header 'accept: application/json'      --header 'content-type: application/json'      --data '
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "zkevm_batchNumberByBlockNumber",
  "params": [
    "0xB58F67"
  ]
}
'
< {"jsonrpc":"2.0","id":1,"result":"0x0"}
````

#### Actual behaviour

````bash
< {"jsonrpc":"2.0","id":1,"result":"0x0"}
````

#### Steps to reproduce the behaviour

1. Launch node, wait until synchronises 
2. Build rpcdaemon
3. Launch rpcdaemon
4. Launch petition

#### Backtrace

When I curl against the node it returns the correct response

```bash
> curl --request POST      --url http://localhost:8550/    --header 'accept: application/json'      --header 'content-type: application/json'      --data '
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "zkevm_batchNumberByBlockNumber",
  "params": [
    "0xB58F67"
  ]
}

< {"jsonrpc":"2.0","id":1,"result":"0x1eb41d"}
```
