### ISSUE TITLE
Txpool Locks Up with Fuzzed Txs

### ISSUE THREAD

**Issue by praetoriansentry** [0xPolygon/cdk-erigon#851]
#### System information

Erigon version: cdk-erigon version 2.43.0-dev / hermeznetwork/cdk-erigon:beta13-candidate3-5225235-amd64

OS & Version: Linux straylight 6.9.10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.9.10-1 (2024-07-19) x86_64 GNU/Linux

Commit hash: 

Erigon Command (with flags/config): cdk-erigon --pprof=true --pprof.addr 0.0.0.0 --config /etc/cdk-erigon/config.yaml

```yaml
datadir: ./data/dynamic-kurtosis-sequencer
chain: dynamic-kurtosis

http.addr: "0.0.0.0"
http.api: [eth, debug, net, trace, web3, erigon, zkevm, txpool]
http.corsdomain: "*"
http.port: 8123
http.vhosts: "*"
http: true

pprof: true
pprof.addr: "0.0.0.0"
pprof.port: "6060"

metrics: true
metrics.port: "9091"
metrics.addr: "0.0.0.0"

private.api.addr: localhost:9092
torrent.port: 42070
txpool.disable: false
ws: true
externalcl: true
log.console.verbosity: debug

zkevm.address-admin: "0xE34aaF64b29273B7D567FCFc40544c014EEe9970"
zkevm.address-ger-manager: "0x1f7ad7caA53e35b4f0D138dC5CBF91aC108a2674"
zkevm.address-rollup: "0x2F50ef6b8e8Ee4E579B17619A92dE3E2ffbD8AD2"
zkevm.address-sequencer: "0x5b06837A43bdC3dD9F114558DAf4B26ed49842Ed"
zkevm.address-zkevm: "0x1Fe038B54aeBf558638CA51C91bC8cCa06609e91"
zkevm.data-stream-host: "0.0.0.0"
zkevm.data-stream-port: 6900
zkevm.datastream-version: 2

zkevm.executor-strict: false
# zkevm.executor-urls: zkevm-prover-001:50071

zkevm.sequencer-batch-seal-time: 12s # 12s
zkevm.sequencer-block-seal-time: 6s # 6s
zkevm.sequencer-non-empty-batch-seal-time: 3s # 3s

zkevm.l1-chain-id: 271828
zkevm.l1-first-block: 1
zkevm.l1-matic-contract-address: "0xEdE9cf798E0fE25D35469493f43E88FeA4a5da0E"
zkevm.l1-rollup-id: 1
zkevm.l1-rpc-url: http://el-1-geth-lighthouse:8545
zkevm.l2-chain-id: 10101

zkevm.rpc-ratelimit: 250
# zkevm.sequencer-initial-fork-id: 9
zkevm.disable-virtual-counters: false
```

Concensus Layer: N/A

Concensus Layer Command (with flags/config): N/A

Chain/Network: Local DevNet

#### Expected behaviour

I take these random (mostly failing) contracts and deploy them rapidly in a loop:
[500-random-contracts.txt](https://github.com/user-attachments/files/16390017/500-random-contracts.txt)

This is the command:
```bash
cur_nonce=$(cast nonce --rpc-url {{ rpc_url }} {{ eth_address }})
gas_price="$(cast gas-price --rpc-url {{ rpc_url }})"
gas_price=$(bc <<< "2 * $gas_price")
cat 500-random-contracts.txt | while read -r line; do
    echo "Contract -- $line" >> 500-random-contracts.out
    cast send {{ legacy_flag }} --async --nonce $cur_nonce --private-key {{ private_key }} --gas-limit 250000 --gas-price $gas_price --rpc-url {{ rpc_url }} -j \
        --create "$line" &>> 500-random-contracts.out
    retVal=$?
    if [[ $retVal -eq 0 ]]; then
        cur_nonce=$((cur_nonce + 1))
    fi
done
```
Against geth, other nodes these contracts are executed fine and execution proceeds normally.

#### Actual behaviour

Most of the time, if I run all of these contracts in a loop, the tx pool will seem to lock up. The node itself is still responsive, but it will stop producing blocks. This is a pprof taken while the node is locked up:

[profile001.pdf](https://github.com/user-attachments/files/16390011/profile001.pdf)

#### Steps to reproduce the behaviour
Start up a erigon network and run the bash script with the fuzzed transactions to cause the txpool to lock up

#### Backtrace

````

1 @ 0x43f20b 0x1194f45 0x1194f16 0x1194eb4 0x1194ca9 0x1194c64 0x11a0495 0x117a962 0x117a3ae 0x117903e 0x1164c42 0x1164c43 0x1163daf 0x13bad7a 0x13b8c46 0x13b7975 0x13b865c 0x17961a5 0x179074a 0x17a2153 0x14cc6cd 0x14cb5e5 0x1f6e92d 0x1f6dfe5 0x49c261
#	0x1194f44	github.com/ledgerwatch/erigon/core/vm.(*CounterCollector).Deduct+0x1c4		github.com/ledgerwatch/erigon/core/vm/zk_counters.go:210
#	0x1194f15	github.com/ledgerwatch/erigon/core/vm.(*CounterCollector).offsetUtil+0x195	github.com/ledgerwatch/erigon/core/vm/zk_counters.go:440
#	0x1194eb3	github.com/ledgerwatch/erigon/core/vm.(*CounterCollector).opCodeCopyLoop+0x133	github.com/ledgerwatch/erigon/core/vm/zk_counters.go:1131
#	0x1194ca8	github.com/ledgerwatch/erigon/core/vm.(*CounterCollector).multiCall+0x7c8	github.com/ledgerwatch/erigon/core/vm/zk_counters.go:824
#	0x1194c63	github.com/ledgerwatch/erigon/core/vm.(*CounterCollector).opExtCodeCopy+0x783	github.com/ledgerwatch/erigon/core/vm/zk_counters.go:1121
#	0x11a0494	github.com/ledgerwatch/erigon/core/vm.WrapJumpTableWithZkCounters.func1.1+0x34	github.com/ledgerwatch/erigon/core/vm/zk_counters.go:226
#	0x117a961	github.com/ledgerwatch/erigon/core/vm.(*EVMInterpreter).RunZk.func2+0x101	github.com/ledgerwatch/erigon/core/vm/interpreter_zkevm.go:216
#	0x117a3ad	github.com/ledgerwatch/erigon/core/vm.(*EVMInterpreter).RunZk+0xdad		github.com/ledgerwatch/erigon/core/vm/interpreter_zkevm.go:270
#	0x117903d	github.com/ledgerwatch/erigon/core/vm.(*EVMInterpreter).Run+0x1d		github.com/ledgerwatch/erigon/core/vm/interpreter.go:195
#	0x1164c41	github.com/ledgerwatch/erigon/core/vm.run+0xde1					github.com/ledgerwatch/erigon/core/vm/evm.go:55
#	0x1164c42	github.com/ledgerwatch/erigon/core/vm.(*EVM).createZkEvm+0xde2			github.com/ledgerwatch/erigon/core/vm/evm_zkevm.go:150
#	0x1163dae	github.com/ledgerwatch/erigon/core/vm.(*EVM).Deploy+0x1ee			github.com/ledgerwatch/erigon/core/vm/evm_zkevm.go:72
#	0x13bad79	github.com/ledgerwatch/erigon/core.(*StateTransition).TransitionDb+0xd99	github.com/ledgerwatch/erigon/core/state_transition.go:391
#	0x13b8c45	github.com/ledgerwatch/erigon/core.ApplyMessage+0x45				github.com/ledgerwatch/erigon/core/state_transition.go:199
#	0x13b7974	github.com/ledgerwatch/erigon/core.ApplyMessageWithTxContext+0x1d4		github.com/ledgerwatch/erigon/core/state_processor_zkevm.go:78
#	0x13b865b	github.com/ledgerwatch/erigon/core.ApplyTransaction_zkevm+0x35b			github.com/ledgerwatch/erigon/core/state_processor_zkevm.go:178
#	0x17961a4	github.com/ledgerwatch/erigon/zk/stages.attemptAddTransaction+0x704		github.com/ledgerwatch/erigon/zk/stages/stage_sequence_execute_transactions.go:226
#	0x1790749	github.com/ledgerwatch/erigon/zk/stages.SpawnSequencingStage+0x5209		github.com/ledgerwatch/erigon/zk/stages/stage_sequence_execute.go:395
#	0x17a2152	github.com/ledgerwatch/erigon/zk/stages.SequencerZkStages.func13+0xb2		github.com/ledgerwatch/erigon/zk/stages/stages.go:109
#	0x14cc6cc	github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage+0x16c		github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:360
#	0x14cb5e4	github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run+0x284			github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:262
#	0x1f6e92c	github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep+0x46c			github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:177
#	0x1f6dfe4	github.com/ledgerwatch/erigon/turbo/stages.StageLoop+0x164			github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:97
````
