### ISSUE TITLE
pprof must be enabled via CLI

### ISSUE THREAD

**Issue by praetoriansentry** [0xPolygon/cdk-erigon#852]
#### System information

Erigon version: cdk-erigon version 2.43.0-dev / hermeznetwork/cdk-erigon:beta13-candidate3-5225235-amd64

OS & Version: Linux straylight 6.9.10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.9.10-1 (2024-07-19) x86_64 GNU/Linux

Commit hash: 

Erigon Command (with flags/config): cdk-erigon --config /etc/cdk-erigon/config.yaml

```yaml
datadir: ./data/dynamic-kurtosis-sequencer
chain: dynamic-kurtosis

http.addr: "0.0.0.0"
http.api: [eth, debug, net, trace, web3, erigon, zkevm, txpool]
http.corsdomain: "*"
http.port: 8123
http.vhosts: "*"
http: true

pprof: true
pprof.addr: "0.0.0.0"
pprof.port: "6060"

metrics: true
metrics.port: "9091"
metrics.addr: "0.0.0.0"

private.api.addr: localhost:9092
torrent.port: 42070
txpool.disable: false
ws: true
externalcl: true
log.console.verbosity: debug

zkevm.address-admin: "0xE34aaF64b29273B7D567FCFc40544c014EEe9970"
zkevm.address-ger-manager: "0x1f7ad7caA53e35b4f0D138dC5CBF91aC108a2674"
zkevm.address-rollup: "0x2F50ef6b8e8Ee4E579B17619A92dE3E2ffbD8AD2"
zkevm.address-sequencer: "0x5b06837A43bdC3dD9F114558DAf4B26ed49842Ed"
zkevm.address-zkevm: "0x1Fe038B54aeBf558638CA51C91bC8cCa06609e91"
zkevm.data-stream-host: "0.0.0.0"
zkevm.data-stream-port: 6900
zkevm.datastream-version: 2

zkevm.executor-strict: false
# zkevm.executor-urls: zkevm-prover-001:50071

zkevm.sequencer-batch-seal-time: 12s # 12s
zkevm.sequencer-block-seal-time: 6s # 6s
zkevm.sequencer-non-empty-batch-seal-time: 3s # 3s

zkevm.l1-chain-id: 271828
zkevm.l1-first-block: 1
zkevm.l1-matic-contract-address: "0xEdE9cf798E0fE25D35469493f43E88FeA4a5da0E"
zkevm.l1-rollup-id: 1
zkevm.l1-rpc-url: http://el-1-geth-lighthouse:8545
zkevm.l2-chain-id: 10101

zkevm.rpc-ratelimit: 250
# zkevm.sequencer-initial-fork-id: 9
zkevm.disable-virtual-counters: false
```

Concensus Layer: N/A

Concensus Layer Command (with flags/config): N/A

Chain/Network: Local DevNet

#### Expected behaviour

Based on the how the rest of the node is configured, I was expecting that I could enable pprof with 3 settings in my config.yml
```yaml
pprof: true
pprof.addr: 0.0.0.0
pprof.port: 6060
```

This type of configuration seems to work for http and prometheus metrics

#### Actual behaviour

When I did this, the node was not listening on port 6060. It seems like these configs do not take effect. In order to enable pprof, I had to add ` --pprof=true --pprof.addr 0.0.0.0` to the comman

#### Steps to reproduce the behaviour
Start up erigon with pprof configured via a config file rather than command like flags.

#### Backtrace

```
NA
```
